[build]
builder = "nixpacks"

[build.nixpacks]
packages = ["nodejs-18_x", "npm-9_x"]

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10