export const storiesNavPrototypes = [
  { id: '1a', name: 'Side Panel — Clean Split', file: 'proto-1a-side-panel-clean.html' },
  { id: '1b', name: 'Side Panel — Elevated', file: 'proto-1b-side-panel-elevated.html' },
  { id: '2a', name: 'Overlay Drawer — Half Width', file: 'proto-2a-overlay-half.html' },
  { id: '2b', name: 'Overlay Drawer — Wide Immersive', file: 'proto-2b-overlay-wide.html' },
  { id: '3a', name: 'Split View — Equal 50/50', file: 'proto-3a-split-equal.html' },
  { id: '3b', name: 'Split View — Sidebar List', file: 'proto-3b-split-sidebar.html' },
  { id: '4a', name: 'Accordion — Smooth Expand', file: 'proto-4a-accordion-smooth.html' },
  { id: '4b', name: 'Accordion — Floating Card', file: 'proto-4b-accordion-floating.html' },
  { id: '5a', name: 'Nav Rail — Icon', file: 'proto-5a-rail-icon.html' },
  { id: '5b', name: 'Nav Rail — Expandable', file: 'proto-5b-rail-expandable.html' },
  { id: '6a', name: 'Hover Peek — Floating', file: 'proto-6a-hover-floating.html' },
  { id: '6b', name: 'Hover Peek — Inline', file: 'proto-6b-hover-inline.html' },
  { id: '7a', name: 'Tabbed Reader — Horizontal', file: 'proto-7a-tabs-horizontal.html' },
  { id: '7b', name: 'Tabbed Reader — Vertical', file: 'proto-7b-tabs-vertical.html' },
  { id: '8a', name: 'Sticky Nav — Breadcrumb', file: 'proto-8a-navbar-breadcrumb.html' },
  { id: '8b', name: 'Sticky Nav — Rich Progress', file: 'proto-8b-navbar-rich.html' },
  { id: '9a', name: 'Peek Strip — Dots', file: 'proto-9a-peek-dots.html' },
  { id: '9b', name: 'Peek Strip — Initials', file: 'proto-9b-peek-initials.html' },
  { id: '10a', name: 'Lightbox — Centered Modal', file: 'proto-10a-lightbox-centered.html' },
  { id: '10b', name: 'Lightbox — Expanding Card', file: 'proto-10b-lightbox-expanding.html' },
];
