import { Router } from 'express';
import {
  createJournalEntry,
  getJournalEntries,
  getJournalEntryById,
  updateJournalEntry,
  deleteJournalEntry,
  bulkDeleteAutoGeneratedDrafts,
  clearDemoData,
  publishJournalEntry,
  toggleLike,
  toggleAppreciate,
  rechronicleEntry,
  recordAnalytics,
  getEntryComments,
  addComment,
  addArtifact,
  getUserRechronicles,
  getUserFeed,
  regenerateNarrative,
  createDraftStory
} from '../controllers/journal.controller';
import { authenticate } from '../middleware/auth.middleware';
import { attachJournalService } from '../middleware/demo-mode.middleware';

const router = Router();

// All journal routes require authentication and request-scoped JournalService
router.use(authenticate);
router.use(attachJournalService);

// Journal entry CRUD
router.get('/entries', getJournalEntries);
router.get('/feed', getUserFeed); // User feed with rechronicles
router.get('/rechronicles', getUserRechronicles); // User rechronicles
router.post('/entries', createJournalEntry);
// Bulk delete must come before :id routes to avoid routing conflicts
router.delete('/entries/bulk/auto-generated', bulkDeleteAutoGeneratedDrafts);
// Clear all data for current mode (demo or production based on X-Demo-Mode header)
router.delete('/entries/bulk/all', clearDemoData);
router.get('/entries/:id', getJournalEntryById);
router.put('/entries/:id', updateJournalEntry);
router.delete('/entries/:id', deleteJournalEntry);

// Publishing
router.post('/entries/:id/publish', publishJournalEntry);

// Narrative regeneration
router.post('/entries/:id/regenerate', regenerateNarrative);

// Create draft story from selected activities
// POST /api/v1/journal/draft-stories
// Body: { activityIds: string[], groupingMethod: 'manual', workspaceId: string, ... }
router.post('/draft-stories', createDraftStory);

// Social interactions
router.post('/entries/:id/like', toggleLike);
router.post('/entries/:id/appreciate', toggleAppreciate);
router.post('/entries/:id/rechronicle', rechronicleEntry);

// Comments
router.get('/entries/:id/comments', getEntryComments);
router.post('/entries/:id/comments', addComment);

// Artifacts
router.post('/entries/:id/artifacts', addArtifact);

// Analytics
router.post('/entries/:id/analytics', recordAnalytics);

export default router;